

-- 2. TABLAS BASE (SIN DEPENDENCIAS)
CREATE TABLE PLAN (
    id_plan NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_plan VARCHAR2(20) NOT NULL CHECK (nombre_plan IN ('Básico', 'Estándar', 'Premium')),
    precio NUMBER(10,2) NOT NULL,
    calidad_video VARCHAR2(20),
    cantidad_pantallas NUMBER(2),
    perfiles_permitidos NUMBER(2) NOT NULL
);

CREATE TABLE CATEGORIA (
    id_categoria NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE GENERO (
    id_genero NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE DEPARTAMENTO (
    id_departamento NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL UNIQUE
);

-- 3. TABLAS CON RELACIONES SIMPLES
CREATE TABLE USUARIO (
    id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_completo VARCHAR2(255) NOT NULL,
    correo_electronico VARCHAR2(150) NOT NULL UNIQUE,
    telefono VARCHAR2(20) NOT NULL,
    fecha_nacimiento DATE NOT NULL,
    ciudad_residencia VARCHAR2(100) NOT NULL,
    clasificacion_edad VARCHAR2(5) NOT NULL CHECK (clasificacion_edad IN ('TP', '+7', '+13', '+16', '+18')),
    estado_cuenta VARCHAR2(15) DEFAULT 'Activo' CHECK (estado_cuenta IN ('Activo', 'Suspendido')),
    id_referente NUMBER,
    descuento_referido NUMBER(5,2) DEFAULT 0,
    CONSTRAINT fk_usuario_ref FOREIGN KEY (id_referente) REFERENCES USUARIO(id_usuario)
);

CREATE TABLE CUENTA (
    id_cuenta NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER NOT NULL UNIQUE,
    id_plan NUMBER NOT NULL,
    estado_servicio VARCHAR2(20) DEFAULT 'Activo',
    fecha_ultimo_pago DATE,
    CONSTRAINT fk_cuenta_user FOREIGN KEY (id_usuario) REFERENCES USUARIO(id_usuario),
    CONSTRAINT fk_cuenta_plan FOREIGN KEY (id_plan) REFERENCES PLAN(id_plan)
);

CREATE TABLE EMPLEADO (
    id_empleado NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_completo VARCHAR2(255) NOT NULL,
    correo VARCHAR2(150) NOT NULL,
    id_departamento NUMBER NOT NULL,
    id_supervisor NUMBER,
    CONSTRAINT fk_emp_depto FOREIGN KEY (id_departamento) REFERENCES DEPARTAMENTO(id_departamento),
    CONSTRAINT fk_emp_sup FOREIGN KEY (id_supervisor) REFERENCES EMPLEADO(id_empleado)
);

-- 4. CONTENIDO (DEPENDE DE EMPLEADO Y CATEGORIA)
CREATE TABLE CONTENIDO (
    id_contenido NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR2(255) NOT NULL,
    tipo_contenido VARCHAR2(20) CHECK (tipo_contenido IN ('Película', 'Serie', 'Podcast')),
    es_original NUMBER(1) DEFAULT 0,
    id_empleado_resp NUMBER,
    id_categoria NUMBER NOT NULL,
    CONSTRAINT fk_cont_emp FOREIGN KEY (id_empleado_resp) REFERENCES EMPLEADO(id_empleado),
    CONSTRAINT fk_cont_cat FOREIGN KEY (id_categoria) REFERENCES CATEGORIA(id_categoria)
);

-- 5. PERFILES (DEPENDE DE CUENTA)
CREATE TABLE PERFIL (
    id_perfil NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cuenta NUMBER NOT NULL,
    nombre VARCHAR2(50) NOT NULL,
    avatar VARCHAR2(500),
    tipo_perfil VARCHAR2(15) CHECK (tipo_perfil IN ('Adulto', 'Infantil')),
    CONSTRAINT fk_perfil_cta FOREIGN KEY (id_cuenta) REFERENCES CUENTA(id_cuenta)
);

-- 6. TABLAS QUE DEPENDEN DE PERFIL O CONTENIDO (AQUÍ ESTABA EL ERROR)
CREATE TABLE FAVORITO (
    id_favorito NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_perfil NUMBER NOT NULL,
    id_contenido NUMBER NOT NULL,
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_fav_perf FOREIGN KEY (id_perfil) REFERENCES PERFIL(id_perfil),
    CONSTRAINT fk_fav_cont FOREIGN KEY (id_contenido) REFERENCES CONTENIDO(id_contenido)
);

CREATE TABLE CALIFICACION (
    id_calificacion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_perfil NUMBER NOT NULL,
    id_contenido NUMBER NOT NULL,
    estrellas NUMBER(1) CHECK (estrellas BETWEEN 1 AND 5),
    CONSTRAINT fk_cal_perf FOREIGN KEY (id_perfil) REFERENCES PERFIL(id_perfil),
    CONSTRAINT fk_cal_cont FOREIGN KEY (id_contenido) REFERENCES CONTENIDO(id_contenido)
);